### ISSUE TITLE
Go PURL possible interpretations

### ISSUE THREAD

**Issue by zinderic** [package-url/purl-spec#290]
Looks like the current spec doesn't offer canonical definition for what PURL should look like for Go. For example I see that:

* https://github.com/microsoft/sbom-tool uses this:

pkg:github/mattn/go-runewidth@v0.0.9

* https://github.com/anchore/syft on the other hand does this:

pkg:golang/github.com/RoaringBitmap/roaring@v1.6.0

Notice that those are different ways of using the `type` and `namespace` and both appear correct from what I read in the spec. Shouldn't there be one canonical way? Which one is the correct one for Go?

**Comment by matt-phylum** [comment]
Go PURLs are documented [here](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#golang), but I think it's outdated. Go modules have versions and the spec doesn't mention them at all, but putting the version tag in place of the commit hash seems like the right thing to do.

`pkg:github/mattn/go-runewidth@v0.0.9` is a GitHub package, not a Go package.

`pkg:go/github.com/RoaringBitmap/roaring@v1.6.0` (go instead of golang) or `pkg:github.com/RoaringBitmap/roaring@v1.6.0` (github.com) would be incorrect.

**Comment by zinderic** [comment]
This is actually a valid Go package:

```
github.com/mattn/go-runewidth@v0.0.9
```

The PURL was missing .com in the domain name but it should still refer to a Go package. Not having a `type` defined doesn't help communicate that. So, the canonical Go type is "goland"?

**Comment by matt-phylum** [comment]
`github.com/mattn/go-runewidth@v0.0.9` is a Go package in Go's language, but `pkg:github/mattn/go-runewidth@v0.0.9` is not a Go package in PURL's language, and `pkg:github.com/mattn/go-runewidth@v0.0.9` is not a PURL at all. It should be `pkg:golang/github.com/mattn/go-runewidth@v0.0.9`.

**Comment by zinderic** [comment]
Understood, thanks for clarifying!
