### ISSUE TITLE
Automatic PURL generation from existing CPE or CSAF

### ISSUE THREAD

**Issue by adulau** [package-url/purl-spec#331]
We wanted to add an automatic PURL generation from existing CPE or CSAF in [vulnerability-lookup](https://github.com/cve-search/vulnerability-lookup). Is there a library for doing this?

**Comment by bureado** [comment]
I'm aware of crosswalks like https://github.com/scanoss/purl2cpe and https://github.com/aboutcode-org/vulnerablecode-purl2cpe but not quite a library.

**Comment by adulau** [comment]
Thanks a lot @bureado for the exhaustive list.  Just wondering about the direction, it's mainly from purl to CPE but not the reverse. Is there a specific reason to that ?

**Comment by bureado** [comment]
@adulau for both projects I referenced above, it should be possible to get an array of purls given a CPE. But the question you bring up is, I think, very central to the broader problem.

Here's an example: the software entity that humans know as "nginx", more precisely the web server typically called "nginx", is recognized in scanoss/purl2cpe as `` (https://github.com/scanoss/purl2cpe/blob/main/data/nginx/nginx/cpes.yml) and as a purls[].sizeof == 6 including `pkg:deb/debian/nginx`, `pkg:github/nginx/nginx`, and more.

But we also know that binary nginx can be any of https://repology.org/project/nginx/packages in various *nixes and package managers, and even `pkg:github/nginx/nginx` doesn't have much more specificity - which branch/tag? Which commit reference? Once I'm in source world, then searches like https://whatsrc.org/search?q=nginx make the problem a bit more complicated.

Good opportunity to add a couple more relevant projects:

1. https://github.com/spice-labs-inc/goatrodeo
2. https://github.com/kpcyrd/what-the-src

And lastly, an approach that uses WikiData's ontology:

1. https://github.com/ossf/wg-securing-critical-projects/issues/41
2. https://github.com/ossf/package-feeds/issues/203#issuecomment-1176862960

I'm eager to collaborate in this space; sorry my comments have distracted from your original question, but I truly think there are a few efforts that could potentially cross-pollinate towards this goal.

**Comment by andrewpollock** [comment]
Greetings! From my adventures in this space, particularly across project boundaries, I've found it's rather important to level-set on the language of CPE, because it means different things to different people and some of it's dependent on what you're actually trying to achieve.

From https://github.com/CVEProject/quality-workgroup/issues/12#issuecomment-2263765190, there is a good enumeration (no pun intended) of the various different "types" of CPEs and how they're able to be used.

So, @adulau when you say:

> We wanted to add an automatic PURL generation from existing CPE or CSAF in [vulnerability-lookup](https://github.com/cve-search/vulnerability-lookup)

stepping back for a moment, could you drop in a few worked examples of the desired inputs and outputs?

**Comment by pombredanne** [comment]
@adulau 👋  re:

> We wanted to add an automatic PURL generation from existing CPE or CSAF in vulnerability-lookup. Is there a library for doing this?

- @andrewpollock 's point make sense. IMHO, the only thing that could be sanely mapped to PURL are CPE names. Configuration and wildcard are problematic. And the version ranges could be expressed as VERS too in a more straightforward way.

- also @bureado pointed to https://github.com/aboutcode-org/vulnerablecode-purl2cpe : this has been kept current; this is based on automatically traversing the graph of relationships between PURLs and CVEs in vulnerablecode and has been highly unreliable

- since CPE names are given names, anything but a hand made mapping will be unreliable, with the caveat that it is is not one to one, and @bureado pointed, e.g., one CPE can point to multiple PURLs.

Any automatic PURL generation from existing CPE is IMHO a lost cause (unless we add a cpe PURL type, but that would just move the problem without resolving it). It needs a proper mapping. And a library could then use the mapping. 

It makes sense to maintain here a reference an open PURL <-> CPE mapping and I see it being a useful community asset. But it needs to be curated by humans to have any value. 

Or quoting @andrewpollock we need this:
> https://www.first.org/resources/papers/vulncon2024/VulnCon-The-Trials-and-Tribulations-of-Bulk-Converting-CVEs-to-OSV-Pollock.pdf#page=38
> Andrew’s Data Quality Wishlist
> ....
> Comprehensive, open and free mapping between CPEs, Purls and canonical Git repositories

( @andrewpollock side note for the "Purls and canonical Git repositories" part, I have some WIP with PurlDB towards publishing and unlocking all that data)

**Comment by andrewpollock** [comment]
> ( @andrewpollock side note for the \"Purls and canonical Git repositories\" part, I have some WIP with PurlDB towards publishing and unlocking all that data)

Ooh please keep me posted!

**Comment by adulau** [comment]
Thanks to all for the detailed feedback.

Quick question following @pombredanne feedback. 

> Any automatic PURL generation from existing CPE is IMHO a lost cause (unless we add a cpe PURL type, but that would just move the problem without resolving it). It needs a proper mapping. And a library could then use the mapping.

What is the exact definition of "proper mapping"?  I mean we discussed internally to go further by either providing an actual improved directory of combined CPE. Especially allowing vendor and products to have aliases or following names as software and vendor names change regularly.  It also seems we cannot reference a software without a package in purl. 

We will work on improving the actual CPE directory and see how we link the associated packages to PURL in vulnerability-lookup.

I'll close the issue for the time being until we implement the PURL part in vulnerability-lookup.

**Comment by pombredanne** [comment]
@adulau FYI, I have been invited by a CVE.org quality working group to present PURL sometimes in January 2025 as they would be interested to have it as a main id in the next CVE schema. To be continued...
