### ISSUE TITLE
Rename docker with ociimage

### ISSUE THREAD

**Issue by dol** [package-url/purl-spec#68]
Docker images are standardized under the OCI image specification. https://github.com/opencontainers/image-spec
Docker is only one vendor that support the image spec.

**Comment by stevespringett** [comment]
PURL does not describe the 'what', it describes the 'how'. From the readme:

> reliably identify and locate software

For example, PURL describes maven, gradle, and sbt for Java. All three resolve Java JARs, but locate the jars in different ways. Different APIs, different registry formats, etc.

The OCI image specification does not describe how images are located, it describes the image format itself.

The OCI distribution spec however, does describe the 'how'. It describes the REST APIs that Docker Hub uses. The spec is is a work in progress and will likely become a superset of the capabilities available from Docker hub.

Because it may become a superset, I don't see oci replacing docker as a PURL type, rather being a future addition to the PURL spec.

**Comment by iamwillbar** [comment]
Based on the discussion above I'm going to go ahead and close this issue. If we'd like to add an `oci` type please go ahead and open an issue (or even better a pull request) for that.

**Comment by dol** [comment]
This is ok for me. @stevespringett Thank you for your explanation. Make sense.

**Comment by pombredanne** [comment]
@iamwillbar you wrote:

> If we'd like to add an oci type please go ahead and open an issue (or even better a pull request) for that.

Actually that sounds very much as a  qualifier to me (and in fact with some registries such as gcr.io you can pull an image in Docker or OCI format AFAICR)
