### ISSUE TITLE
Stricter validation for known types

### ISSUE THREAD

**Issue by RikardLegge** [package-url/purl-spec#87]
Been using the PURL spec for a while now and have started bumping into issues with valid PURLs not being valid package qualifier names. 

Currently, for golang, the following description is provided in the PURL specification:
* There is no default package repository: this is implied in the namespace using the go get command conventions
* The namespace and name must be lowercased.
* The subpath is used to point to a subpath inside a package
* The version is often empty when a commit is not specified and should be the commit in most cases when available.

This description allows entering invalid purls. For example `pkg:golang/purl/spec` is treated as a local package, so not accessible for any other machine. `pkg:golang/purl.com/spec` is on the other hand treated as a package named `spec` which can be found at the domain `purl.com`. At least in our internal models, the former is an invalid package name while the latter is valid. The same can be said for many other package managers and VCS repositories like `github` or `bitbucket`, which all have their own validation rules.

Before spending time to internally define what we classify as valid PURL:s, I wanted to get your input on whether this type of stricter validation belong in the `purl-spec` for known types or if it's more suitable as a separate package?

The major downside of limiting what is seen as a valid package is that updates to the package manager/repository might invalidate the limiting assumptions. On the other hand, if it's impossible for a PURL to be interpreted as a valid package, is it a valid PURL?

**Comment by jdillon** [comment]
Looks like both of these are valid pacakge-urls:

* `pkg:golang/purl/spec`
* `pkg:golang/purl.com/spec`

Both with a name = `spec` and a variance of namespace of [ `purl` and `purl.com` ]

IIUC the semantics of accessible locally vs. remotely is not expressed by the package-url specification, nor do I think it should be.  I don't think it should dictate case either and it may be relevant to the ask here for stricter validation.  Since purl presently can't no about any future package types and their various limitations or restrictions, and that the primary goal of purl (as I see it) is to define a standard for package coordinate interchange.  Putting more emphasis onto the parsers to perform all means of package coordinate validation is simply not practical.  What is practical is to normalize how the core concepts of a purl are normalized so that type, namespace, name, version, qualifiers and subpath can be extracted universally by a tool and then interpreted as needed.

If the purl spec insists upon more validation and constraints for case and content, the only result is that every parser for the specification will be actually inconsistent, perhaps eventually consistent, assuming that folks go and update their implementations.  But having more complex format specific rules and validation implies that at any one time any package-url parser is probably going to be wrong, as it may not have implemented rules for some new format, or may not have implemented changes to and existing format.

What it can do however, very much like how the URI and URL specifications work is ensure that the core components of a package-url (scheme, type, namespace, name, version, qualifiers, subpath) are well formed, such that a tool can read (and write) these and any other tool supporting the purl specification can do so as well.

I believe that anything more than this is harmful and impossible to implement across systems sanely.  I further believe that if you are using a package format that forbids uppercase package names, then if you are given a purl which is all uppercase, then its a valid purl, but may be invalid (or missing) for the specific ecosystem which the purl represents.

For example to take Maven as an example, w/o purl and only looking at the URI for a specific reference of the package:

This is a valid URI for the junit 4.13 jar package on maven-central:

* https://repo1.maven.org/maven2/junit/junit/4.13/junit-4.13.jar

This is a valid URI ... but since Maven is case-sensitive, this is a 404 and not a valid reference to a package:

* https://repo1.maven.org/maven2/JUNIT/junit/4.13/junit-4.13.jar

Both of these however are valid URIs and systems that understand URI can read this format and comprehend the scheme, the host, the path etc from the string.

Imagine if the URI (and URL) specification had to be aware of all the case-sensitive URI/URL use-cases across the internet and impose some sort of validation scheme onto the parsing of those strings to valid they were sane.  And imagine if web-browsers now had to be aware of each website and what the URI-scheme was, for the content it exposed and what the case of certain path elements were, etc.  If the designers of URI had imposed that sort of limitations, the internet would not exist today, folks would have gotten frustrated with the synchronization needed to keep the URI parsers compatible and given up and rightly so because it wouldn't have made any sense in a massively global and scalable use-case.

* * *

FTR I think that the purl specification should be split up (and I recall seeing something about this) into its core URI form with strict rules on parsing and rendering.  And then per-format/ecosystem rules about how to apply the core PURL semantics to that ecosystem.

I do not believe that the core PURL specification should be worried about or bothered with these format/ecosystem semantics, though I think there is some possibility for extensions which apply format/ecosystem specific validations for warning purposes; but I do not believe that should be part of any core PURL parser.

Keeping these 2 concerns separate allows for all manners of parsers and renders to understand the core PURL specification, and for folks that need additional validation or warnings could use some sort of format/ecosystem schema validation on top of purl.  But this sounds a lot more to me like an additional specification to define the schema of a purl type based on the core purl components, than it does as the core purl specification.

**Comment by RikardLegge** [comment]
@jdillon Thank you for a well written reply. It's really appreciated.

Separating the core from ecosystem specific rules sounds like a wise stance. I understand that in the general case, both of the example PURL:s technically are valid. Will keep our validation internal for the time being and keep updated on how the discussion about ecosystem specific rules progresses.
